refactor(security): Replaced the use of WebSecurityConfigurerAdapter with a configuration that defines SecurityFilterChain bean.
The error occurs because WebSecurityConfigurerAdapter has been deprecated and removed in Spring Security 6.x, which is used by Spring Boot 3.x.

Error details for reference:
````
kayenta/kayenta-web/src/main/java/com/netflix/kayenta/config/WebSecurityConfig.java:23: error: cannot find symbol
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
                                                                       ^
  symbol:   class WebSecurityConfigurerAdapter
  location: package org.springframework.security.config.annotation.web.configuration
kayenta/kayenta-web/src/main/java/com/netflix/kayenta/config/WebSecurityConfig.java:35: error: cannot find symbol
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
                                       ^
  symbol: class WebSecurityConfigurerAdapter
````
Reference Links:
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter