fix(dependency): Issue of missing javax.validation:validation-api dependency while upgrading the spring cloud to Hoxton.SR12 in kork (#1010)
While upgrading spring cloud to Hoxton.SR12, we encountered below errors :

> Task :igor-core:compileGroovy
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactDecorationProperties.java:20: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactDecorationProperties.java:21: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotEmpty;
                                   ^
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactTemplateProperties.java:24: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactTemplateProperties.java:25: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotEmpty;
                                   ^
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/service/ArtifactDecorator.java:29: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactDecorationProperties.java:33: error: cannot find symbol
  @Valid private List<FileDecorator> fileDecorators;
   ^
  symbol:   class Valid
  location: class ArtifactDecorationProperties
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactDecorationProperties.java:37: error: cannot find symbol
    @NotEmpty private String type;
     ^
  symbol:   class NotEmpty
  location: class FileDecorator
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactDecorationProperties.java:38: error: cannot find symbol
    @NotEmpty private String decoratorRegex;
     ^
  symbol:   class NotEmpty
  location: class FileDecorator
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactDecorationProperties.java:39: error: cannot find symbol
    @NotEmpty private String identifierRegex;
     ^
  symbol:   class NotEmpty
  location: class FileDecorator
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactTemplateProperties.java:37: error: cannot find symbol
  @Valid private List<CustomTemplateConfig> templates = new ArrayList<>();
   ^
  symbol:   class Valid
  location: class ArtifactTemplateProperties
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactTemplateProperties.java:42: error: cannot find symbol
    @NotEmpty private String name;
     ^
  symbol:   class NotEmpty
  location: class CustomTemplateConfig
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactTemplateProperties.java:44: error: cannot find symbol
    @NotEmpty private String templatePath;
     ^
  symbol:   class NotEmpty
  location: class CustomTemplateConfig
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/service/ArtifactDecorator.java:44: error: cannot find symbol
      @Valid ArtifactDecorationProperties artifactDecorationProperties) {
       ^
  symbol:   class Valid
  location: class ArtifactDecorator
13 errors
startup failed:
Compilation failed; see the compiler error output for details.

1 error

> Task :igor-core:compileGroovy FAILED
======================

> Task :igor-monitor-travis:compileGroovy
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisConfig.java:37: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisProperties.java:26: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotEmpty;
                                   ^
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisConfig.java:64: error: cannot find symbol
      @Valid TravisProperties travisProperties,
       ^
  symbol:   class Valid
  location: class TravisConfig
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisProperties.java:38: error: cannot find symbol
  @Valid private List<TravisHost> masters;
   ^
  symbol:   class Valid
  location: class TravisProperties
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisProperties.java:39: error: cannot find symbol
  @Valid private List<String> regexes;
   ^
  symbol:   class Valid
  location: class TravisProperties
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisProperties.java:58: error: cannot find symbol
    @NotEmpty private String name;
     ^
  symbol:   class NotEmpty
  location: class TravisHost
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisProperties.java:59: error: cannot find symbol
    @NotEmpty private String baseUrl;
     ^
  symbol:   class NotEmpty
  location: class TravisHost
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisProperties.java:60: error: cannot find symbol
    @NotEmpty private String address;
     ^
  symbol:   class NotEmpty
  location: class TravisHost
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisProperties.java:61: error: cannot find symbol
    @NotEmpty private String githubToken;
     ^
  symbol:   class NotEmpty
  location: class TravisHost
9 errors
startup failed:
Compilation failed; see the compiler error output for details.

1 error

> Task :igor-monitor-travis:compileGroovy FAILED

The root cause is missing javax.validation:validation-api dependency, the reason being upgrade of transitive dependency resilience4j from 1.0.0 to 1.7.0 while upgrade to Hoxton.SR12.

https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-framework-common/1.0.0

https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-framework-common/1.7.0

To fix this issue we require to explicitly implement the dependency in gradle file of respective module.