fix(orca/retrofit2): fix OrcaFixtureTest failure by including kork-retrofit2 module in orca-retrofit.
$ ./gradlew orca:orca-api-tck:test --tests OrcaFixtureTest

...

Caused by:
org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.clouddriver.OortService]: Factory method 'oortDeployService' threw exception; nested exception is com.netflix.spinnaker.kork.exceptions.SystemException: No service client provider found for url (https://clouddriver-readonly.net)
    at app//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
    at app//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648)
    ... 252 more
  Caused by:
    com.netflix.spinnaker.kork.exceptions.SystemException: No service client provider found for url (https://clouddriver-readonly.net)"

...

This fails because the previous commit implements RetrofitServiceFactory.supports to only
return true for retrofit1.  Add a dependency on kork-retrofit2 so Retrofit2ServiceFactory
is present.  This is the correct factory to use since OortService uses retrofit2
annotations.

CloudDriverConfiguration is the class that provides the oortDeployService bean.
CloudDriverConfiguration.java lives in orca-clouddriver, so it could make sense to add the
kork-retrofit2 dependency there.  But, orca-retrofit is a more central place.  Putting the
kork-retrofit2 dependency there ensures that Retrofit2ServiceClientFactory is present
everywhere it needs to be.