fix(config): add @Autowired for DynamicConfigService injection during Spring Boot 3 migration
As part of the Spring Boot 3 migration, added @Autowired to the constructor of
QuietPeriodIndicatorConfigurationProperties to ensure proper injection of DynamicConfigService.
Without this, the bean was not initialized correctly, causing a NullPointerException.

Error:
```
2025-07-31T04:49:29.035Z  INFO 1 --- [readScheduler-1] c.n.s.e.p.monitor.TriggerMonitor         : Found matching pipeline jul30app1:pl1
2025-07-31T04:49:29.036Z ERROR 1 --- [readScheduler-1] c.n.s.e.p.orca.PipelineInitiator         : Unable to trigger pipeline Pipeline(jul30app1, pl1, 928486ab-2402-4813-a24d-4ad5c6e5e4e0): {}

java.lang.NullPointerException: Cannot invoke "com.netflix.spinnaker.kork.dynamicconfig.DynamicConfigService.isEnabled(String, boolean)" because "this.dynamicConfigService" is null
	at com.netflix.spinnaker.echo.config.QuietPeriodIndicatorConfigurationProperties.isEnabled(QuietPeriodIndicatorConfigurationProperties.java:67) ~[echo-pipelinetriggers.jar:na]
	at com.netflix.spinnaker.echo.pipelinetriggers.QuietPeriodIndicator.isEnabled(QuietPeriodIndicator.java:50) ~[echo-pipelinetriggers.jar:na]
	at com.netflix.spinnaker.echo.pipelinetriggers.QuietPeriodIndicator.inQuietPeriod(QuietPeriodIndicator.java:63) ~[echo-pipelinetriggers.jar:na]
	at com.netflix.spinnaker.echo.pipelinetriggers.orca.PipelineInitiator.startPipeline(PipelineInitiator.java:123) ~[echo-pipelinetriggers.jar:na]
	at com.netflix.spinnaker.echo.pipelinetriggers.monitor.TriggerMonitor.lambda$triggerMatchingPipelines$1(TriggerMonitor.java:83) ~[echo-pipelinetriggers.jar:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at com.netflix.spinnaker.echo.pipelinetriggers.monitor.TriggerMonitor.triggerMatchingPipelines(TriggerMonitor.java:80) ~[echo-pipelinetriggers.jar:na]
	at com.netflix.spinnaker.echo.pipelinetriggers.monitor.TriggerMonitor.processEvent(TriggerMonitor.java:62) ~[echo-pipelinetriggers.jar:na]
	at com.netflix.spinnaker.echo.pipelinetriggers.monitor.TriggerEventListener.processEvent(TriggerEventListener.java:62) ~[echo-pipelinetriggers.jar:na]
	at com.netflix.spinnaker.echo.events.EventPropagator.lambda$processEvent$0(EventPropagator.java:71) ~[echo-core.jar:na]
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$wrapCallableForPrincipal$0(AuthenticatedRequest.java:272) ~[kork-security.jar:na]
	at com.netflix.spinnaker.echo.events.EventPropagator.lambda$processEvent$2(EventPropagator.java:78) ~[echo-core.jar:na]
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63) ~[rxjava-3.1.8.jar:na]
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202) ~[rxjava-3.1.8.jar:na]
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256) ~[rxjava-3.1.8.jar:na]
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) ~[rxjava-3.1.8.jar:na]
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56) ~[rxjava-3.1.8.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
```