fix(integration-tests): change testCompileOnly dependencies to testImplementation (#907)
since tests fail with testCompileOnly (introduced in https://github.com/spinnaker/kayenta/pull/895, previously testCompile) like:

Caused by:
java.lang.NumberFormatException: For input string: "${management.server.port}"

but apparently we've gotten numb to integration test failures for one reason or another.

https://docs.gradle.org/6.8.1/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
recommends testImplementation instead of testCompile.