refactor(eureka): removed deprecated client and refactor constructor code during upgrade of spring boot 3.0.x
While upgrading the spring boot to 3.0.13 and spring cloud 2022.0.5, encountered the below errors during build process of kork-eureka module:
```
> Task :kork-eureka:compileJava FAILED
/kork/kork-eureka/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaAutoConfiguration.java:55: error: cannot find symbol
      DiscoveryClient.DiscoveryClientOptionalArgs optionalArgs) {
                     ^
  symbol:   class DiscoveryClientOptionalArgs
  location: class DiscoveryClient
/kork/kork-eureka/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaAutoConfiguration.java:89: error: cannot find symbol
  DiscoveryClient.DiscoveryClientOptionalArgs optionalArgs(
                 ^
  symbol:   class DiscoveryClientOptionalArgs
  location: class DiscoveryClient
2 errors
```
Spring cloud upgrade from 2021.0.x to 2022.0.x also upgrades the eureka client transitively from [1.10.17](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies/2021.0.8) to [2.0.1](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies/2022.0.5)
Eureka client 2.0.x is not backward compatible with 1.0.x. The constructor has also introduced new parameter. So, update the code accordingly.
https://github.com/Netflix/eureka/releases/tag/v2.0.0