fix(security): Disable authenticating internal APIs.
As part of springboot 3 upgrade, security is enabled by default so we need to disable it.

Error:
```
25-06-09T16:12:26.631+05:30 ERROR 35718 --- [o-auto-1-exec-1] c.n.s.k.w.e.GenericExceptionHandlers     : Internal Server Error

java.lang.NullPointerException: Cannot invoke "org.springframework.security.core.Authentication.getName()" because "auth" is null
  at com.netflix.spinnaker.clouddriver.deploy.DescriptionAuthorizerService.authorize(DescriptionAuthorizerService.java:115) ~[clouddriver-core.jar:na]
  at com.netflix.spinnaker.clouddriver.deploy.DescriptionAuthorizerService.authorize(DescriptionAuthorizerService.java:56) ~[clouddriver-core.jar:na]
  at com.netflix.spinnaker.clouddriver.deploy.DefaultDescriptionAuthorizer.authorize(DefaultDescriptionAuthorizer.java:32) ~[clouddriver-core.jar:na]
  at com.netflix.spinnaker.clouddriver.orchestration.OperationsService.lambda$convert$5(OperationsService.java:197) ~[clouddriver-core.jar:na]
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
  at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
  at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[na:na]
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
  at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
  at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[na:na]
  at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
  at java.base/jav

```