refactor: update import for IntervalFunction due to Resilience4j package change
Updated import of IntervalFunction from io.github.resilience4j.retry.IntervalFunction to io.github.resilience4j.core.IntervalFunction.

This change aligns with Resilience4j 2.x package restructuring, which moved shared utilities to the core module for reuse across components.

Required as part of Spring Boot 3.0.13 and Resilience4j upgrade.

Error:

```
> Task :clouddriver:clouddriver-aws:compileGroovy
spinnaker/clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/deploy/description/DeleteAmazonLaunchConfigurationDescription.java:21: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
@Data
^
spinnaker/clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/AmazonCredentialsParser.java:29: error: cannot find symbol
import io.github.resilience4j.retry.IntervalFunction;
                                   ^
  symbol:   class IntervalFunction
  location: package io.github.resilience4j.retry
1 error
1 warning
startup failed:
```