fix(kork/artifacts/test): keep up with new mocking convention in mockito 5
to remove this failure:
```
DeserializerHookRegistryTest > testExpansion(String, Object) > com.netflix.spinnaker.kork.artifacts.artifactstore.entities.DeserializerHookRegistryTest.testExpansion(String, Object)[4] FAILED
  com.fasterxml.jackson.databind.JsonMappingException at DeserializerHookRegistryTest.java:181
  Caused by: java.lang.NullPointerException at DeserializerHookRegistryTest.java:181
```
with stack trace:
```
com.fasterxml.jackson.databind.JsonMappingException: Cannot invoke "com.netflix.spinnaker.kork.artifacts.model.Artifact.getReference()" because "artifact" is null (through reference chain: java.util.LinkedHashMap["manifests"])
	at app//com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at app//com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at app//com.fasterxml.jackson.databind.deser.std.ContainerDeserializerBase.wrapAndThrow(ContainerDeserializerBase.java:190)
	at app//com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:638)
	at app//com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:449)
	at app//com.netflix.spinnaker.kork.artifacts.artifactstore.entities.MapDeserializerHook.deserialize(MapDeserializerHook.java:54)
	at app//com.netflix.spinnaker.kork.artifacts.artifactstore.entities.MapDeserializerHook.deserialize(MapDeserializerHook.java:38)
	at app//com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer.deserialize(StdDelegatingDeserializer.java:151)
	at app//com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at app//com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at app//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at app//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at app//com.netflix.spinnaker.kork.artifacts.artifactstore.entities.DeserializerHookRegistryTest.testExpansion(DeserializerHookRegistryTest.java:181)
...
Caused by: java.lang.NullPointerException: Cannot invoke "com.netflix.spinnaker.kork.artifacts.model.Artifact.getReference()" because "artifact" is null
	at com.netflix.spinnaker.kork.artifacts.artifactstore.entities.ExpandToMapHandler.handle(ExpandToMapHandler.java:41)
	at com.netflix.spinnaker.kork.artifacts.artifactstore.entities.MapDeserializerHook.visit(MapDeserializerHook.java:76)
	at com.netflix.spinnaker.kork.artifacts.artifactstore.entities.MapDeserializerHook.deserialize(MapDeserializerHook.java:55)
	at com.netflix.spinnaker.kork.artifacts.artifactstore.entities.MapDeserializerHook.deserialize(MapDeserializerHook.java:38)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializer.java:444)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:623)
```
See
https://github.com/mockito/mockito/wiki/Draft-Mockito-5-release-notes#what-is-the-effect-of-this-new-method.

ExpandToMapHandler calls ArtifactStore.get with no ArtifactDecorators, so update the mock to
that in the mockito 5 way.