Update GKE version to 1.9.7-gke.3
When running the codelab https://codelabs.developers.google.com/codelabs/cloud-spinnaker-kubernetes-cd/ I see this error: 

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=master version "1.8.8-gke.0" is unsupported.
```

The codelab remains unusable after this, there's no recovery. 
This proposed fix takes the currently latest table gke version to fix that. 

After merging, the files on gs://gke-spinnaker-codelab/install.tgz would also need to get fixed.