chore(dependencies): Autobump korkVersion (#6155)
* chore(dependencies): Autobump korkVersion

* fix(sql/test): render list as a string in saga_ids field of tasks table in SqlTaskCleanupAgentTest

jooq 3.14.16 complains:

        Caused by:
        java.sql.SQLException: Error while writing value at JDBC bind index: 5
            at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:67)
            at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:124)
            ... 120 more

            Caused by:
            org.jooq.exception.SQLDialectNotSupportedException: Type class java.util.ArrayList is not supported in dialect MYSQL

Even if jooq doesn't complain, this feels like the more correct way to provide a value for
this field, and matches what SqlTaskRepository does.

* fix(cats/sql): keep up with API changes from jooq 3.13 to 3.14

See https://www.jooq.org/api-diff/3.13-3.14, https://github.com/jOOQ/jOOQ/issues/10512 and https://github.com/jOOQ/jOOQ/issues/10064.

---------

Co-authored-by: root <root@2b5a6b05cb3f>
Co-authored-by: David Byron <dbyron@salesforce.com>