fix(build): revert java17 changes (#4750)
* Revert "fix(dokka): use version 1.9.20 of org.jetbrains.dokka (#4747)"

This reverts commit af347bb4de17c0c80721ba8acbfe062e60ff0486.

since https://github.com/spinnaker/orca/actions/runs/9490289564/job/26153470376 failed with:

Caused by: java.lang.NoSuchMethodError: 'org.jetbrains.dokka.model.DInterface org.jetbrains.dokka.model.DInterface.copy$default(org.jetbrains.dokka.model.DInterface, org.jetbrains.dokka.links.DRI, java.lang.String, java.util.Map, org.jetbrains.dokka.DokkaConfiguration$DokkaSourceSet, java.util.Map, java.util.List, java.util.List, java.util.List, java.util.Map, org.jetbrains.dokka.model.DObject, java.util.List, java.util.Map, java.util.Set, boolean, org.jetbrains.dokka.model.properties.PropertyContainer, int, java.lang.Object)'

https://github.com/Kotlin/dokka/issues/2452 has some info, but I haven’t been able to make it work.

* Revert "chore(build): enable cross compilation plugin for Java 17 (#4738)"

This reverts commit f936de542bd1a347b5eb39929d4c84bd8ec21ff6.

since $ ./gradlew -PenableCrossCompilerPlugin=true clean orca-api:dokkaJavadoc fails