chore(dependencies): upgrade pf4j from 3.2.0 to 3.10.0 to resolve CVE-2023-40828 (#1153)
pf4j 3.10.0 brings in slf4j-api 2.0.6 which is not compatible with logback 1.2.x.
Upgrading logback created incompatibility issues with Springboot's LogbackLoggingSystem.

> Task :kork-tomcat:test

com.netflix.spinnaker.kork.tomcat.CRLFHeaderTest > clientTest() FAILED
    java.lang.NoClassDefFoundError at LogbackLoggingSystem.java:293
        Caused by: java.lang.ClassNotFoundException at BuiltinClassLoader.java:581

1 test completed, 1 failed
        Caused by: java.lang.ClassNotFoundException at BuiltinClassLoader.java:581

So, pin slf4j-api to 1.7.36 to retain compatibility with logback to 1.2.x.

Removed a test(extensions index is written to META-INF) from TestPluginGeneratorTest.kt as the upgraded pf4j no longer create extensions.idx if no extensions exist.(refer https://github.com/pf4j/pf4j/issues/508)

Note: PluginWrapper is deprecated in 3.10.0 and will be removed in the next major release as per this - https://github.com/pf4j/pf4j/pull/512. So next pf4j upgrade would break the functionality of existing plugins.

Co-authored-by: Kiran Godishala <k.godishala@salesforce.com>
Co-authored-by: Jason <jason.mcintosh@armory.io>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>