refactor(mapper): add custom serializer to handle HttpMethod object during upgrade of spring boot 3.0.x
While upgrading the spring boot to 3.0.13 and spring cloud 2022.0.5, encountered the below error:
```
WebhookServiceSpec > Webhook is being called with correct parameters > com.netflix.spinnaker.orca.webhook.service.WebhookServiceSpec.Webhook is being called with correct parameters [payload: [payload1:Hello, payload2:World!], customHeaders: [:], #1] FAILED
    java.lang.IllegalArgumentException: No serializer found for class org.springframework.http.HttpMethod and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.netflix.spinnaker.orca.pipeline.model.StageContext["method"])
        at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:3442)
        at com.netflix.spinnaker.orca.pipeline.model.StageExecutionImpl.contextToNode(StageExecutionImpl.java:680)
        at com.netflix.spinnaker.orca.pipeline.model.StageExecutionImpl.mapTo(StageExecutionImpl.java:623)
        at com.netflix.spinnaker.orca.pipeline.model.StageExecutionImpl.mapTo(StageExecutionImpl.java:608)
        at com.netflix.spinnaker.orca.webhook.service.WebhookService.getRestTemplateData(WebhookService.java:117)
        at com.netflix.spinnaker.orca.webhook.service.WebhookService.callWebhook(WebhookService.java:65)
        at com.netflix.spinnaker.orca.webhook.service.WebhookServiceSpec.Webhook is being called with correct parameters(WebhookServiceSpec.groovy:99)

        Caused by:
        com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.springframework.http.HttpMethod and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.netflix.spinnaker.orca.pipeline.model.StageContext["method"])

WebhookServiceSpec > Should accept PATCH request FAILED
    Expected no exception to be thrown, but got 'java.lang.IllegalArgumentException'
        at app//spock.lang.Specification.noExceptionThrown(Specification.java:123)
        at com.netflix.spinnaker.orca.webhook.service.WebhookServiceSpec.Should accept PATCH request(WebhookServiceSpec.groovy:201)

        Caused by:
        java.lang.IllegalArgumentException: No serializer found for class org.springframework.http.HttpMethod and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.netflix.spinnaker.orca.pipeline.model.StageContext["method"])
            at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:3442)
            at com.netflix.spinnaker.orca.pipeline.model.StageExecutionImpl.contextToNode(StageExecutionImpl.java:680)
            at com.netflix.spinnaker.orca.pipeline.model.StageExecutionImpl.mapTo(StageExecutionImpl.java:623)
            at com.netflix.spinnaker.orca.pipeline.model.StageExecutionImpl.mapTo(StageExecutionImpl.java:608)
            at com.netflix.spinnaker.orca.webhook.service.WebhookService.getRestTemplateData(WebhookService.java:117)
            at com.netflix.spinnaker.orca.webhook.service.WebhookService.callWebhook(WebhookService.java:65)
            at com.netflix.spinnaker.orca.webhook.service.WebhookServiceSpec.Should accept PATCH request(WebhookServiceSpec.groovy:198)

            Caused by:
            com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.springframework.http.HttpMethod and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.netflix.spinnaker.orca.pipeline.model.StageContext["method"])
                at app//com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
                at app//com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1306)
                at app//com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:408)
                at app//com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:53)
                at app//com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:30)
                at app//com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
                at app//com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
                at app//com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
                at app//com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
                at app//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
                at app//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
                at app//com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:3437)
                ... 6 more

MtlsConfigurationPemTest > mTLSConnectivityPemTest() FAILED
    java.lang.IllegalArgumentException: No serializer found for class org.springframework.http.HttpMethod and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.netflix.spinnaker.orca.pipeline.model.StageContext["method"])
        at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:3442)
        at com.netflix.spinnaker.orca.pipeline.model.StageExecutionImpl.contextToNode(StageExecutionImpl.java:680)
        at com.netflix.spinnaker.orca.pipeline.model.StageExecutionImpl.mapTo(StageExecutionImpl.java:623)
        at com.netflix.spinnaker.orca.pipeline.model.StageExecutionImpl.mapTo(StageExecutionImpl.java:608)
        at com.netflix.spinnaker.orca.webhook.service.WebhookService.getRestTemplateData(WebhookService.java:117)
        at com.netflix.spinnaker.orca.webhook.service.WebhookService.callWebhook(WebhookService.java:65)
        at com.netflix.spinnaker.orca.webhook.config.MtlsConfigurationPemTest.mTLSConnectivityPemTest(MtlsConfigurationPemTest.java:86)

        Caused by:
        com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.springframework.http.HttpMethod and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.netflix.spinnaker.orca.pipeline.model.StageContext["method"])
            at app//com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
            at app//com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1306)
            at
```
The root cause of issue is conversion of `HttpMethod` as class which was previously an enum, in Springframework 6.0. To fix this issue added custom serializer in object mapper.
https://docs.spring.vmware.com/spring-framework/docs/6.0.26/javadoc-api/org/springframework/http/HttpMethod.html
https://github.com/spring-projects/spring-framework/issues/27697