fix(web): allow trailing slashes and disable default security
As part of spirngboot 3.0 upgrade:

- Configured `PathPatternParser` to accept optional trailing slashes globally using `isMatchOptionalTrailingSeparator = true`. This ensures routes like `/poweruser/applications` and `/poweruser/applications/` are treated equally.

  ```
  java.lang.AssertionError: Status expected:<200> but was:<404>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:59)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:122)
	at org.springframework.test.web.servlet.result.StatusResultMatchers.lambda$matcher$9(StatusResultMatchers.java:637)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:214)
	at com.netflix.spinnaker.keel.rest.AdminControllerTests$tests$1$3$3.invoke(AdminControllerTests.kt:148)
	at com.netflix.spinnaker.keel.rest.AdminControllerTests$tests$1$3$3.invoke(AdminControllerTests.kt:143)
	at dev.minutest.TestContextBuilder$test$1.invoke(ContextBuilder.kt:75)
	at dev.minutest.TestContextBuilder$test$1.invoke(ContextBuilder.kt:15)

  ```

- Added a permissive `SecurityFilterChain` bean to disable Spring Security and CSRF protection globally.
  Required due to changes in default Spring Boot 3 security behavior.
  See: https://docs.spring.io/spring-security/reference/servlet/configuration/java.html#jc-httpsecurity

```
ApplicationControllerTests request is forbidden FAILED

  java.lang.AssertionError: Status expected:<403> but was:<500>

ApplicationControllerTests request is forbidden FAILED

  java.lang.AssertionError: Status expected:<403> but was:<500>

ApplicationControllerTests request is forbidden FAILED

  java.lang.AssertionError: Status expected:<403> but was:<500>
```