fix(fiat): roll back fiat to 1.5.1 (#615)
With >= 1.7.0, the logs fill with this error:
groovy.lang.MissingMethodException: No signature of method: com.netflix.spinnaker.fiat.model.resources.Permissions.isEmpty() is applicable for argument types: () values: []

This is because that method was removed in spinnaker/fiat#481