chore(test): adjust test code to execute on arm
Before this, tests would fail because there's no arm docker image for mysql 5.7.22 nor 5.7.34 with errors like:

> Task :orca:orca-sql:test

MySqlPipelineExecutionRepositorySpec > initializationError FAILED
    org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=mysql:5.7.34, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@41c1b23c)
        at app//org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1364)
        at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
        at app//org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
        at app//com.netflix.spinnaker.kork.sql.test.SqlTestUtil.initDualTcDatabases(SqlTestUtil.java:154)
        at app//com.netflix.spinnaker.kork.sql.test.SqlTestUtil.initDualTcMysqlDatabases(SqlTestUtil.java:124)
        at app//com.netflix.spinnaker.orca.sql.pipeline.persistence.MySqlPipelineExecutionRepositorySpec.getDatabase(SqlPipelineExecutionRepositorySpec.groovy:708)

        Caused by:
        com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"no matching manifest for linux/arm64/v8 in the manifest list entries: no match for platform in manifest: not found"}
            at app//org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
            at app//org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
            at java.base@17.0.11.0.101/java.lang.Thread.run(Thread.java:840)

The choice of 8.0.40 for mysql is relatively arbitrary.  It's new enough to have an arm docker image, but the goal of this PR isn't really about updating mysql.