fix(retrofit2): fix a broken scenario related to LegacySignatureCallAdapter (backport #7131) (#7135)
* fix(retrofit2): fix a broken scenario related to LegacySignatureCallAdapter (#7131)

* test(retrofit2): add a test to demonstrate a broken scenario related to LegacySignatureCallAdapter

* fix(retrofit2): fix a broken scenario related to LegacySignatureCallAdapter by passing the retrofit version explicitly

* fix(orca/retrofit2): fix OrcaFixtureTest failure by including kork-retrofit2 module in orca-retrofit.

$ ./gradlew orca:orca-api-tck:test --tests OrcaFixtureTest

...

Caused by:
org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.clouddriver.OortService]: Factory method 'oortDeployService' threw exception; nested exception is com.netflix.spinnaker.kork.exceptions.SystemException: No service client provider found for url (https://clouddriver-readonly.net)
    at app//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
    at app//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648)
    ... 252 more
  Caused by:
    com.netflix.spinnaker.kork.exceptions.SystemException: No service client provider found for url (https://clouddriver-readonly.net)"

...

This fails because the previous commit implements RetrofitServiceFactory.supports to only
return true for retrofit1.  Add a dependency on kork-retrofit2 so Retrofit2ServiceFactory
is present.  This is the correct factory to use since OortService uses retrofit2
annotations.

CloudDriverConfiguration is the class that provides the oortDeployService bean.
CloudDriverConfiguration.java lives in orca-clouddriver, so it could make sense to add the
kork-retrofit2 dependency there.  But, orca-retrofit is a more central place.  Putting the
kork-retrofit2 dependency there ensures that Retrofit2ServiceClientFactory is present
everywhere it needs to be.

* fix(orca-clouddriver): fix OrcaFixtureTest failure by including kork-retrofit2 module in orca-clouddriver

(cherry picked from commit bf30261697586c0da6e2cc15d68f15411abd49b2)

# Conflicts:
#	orca/orca-clouddriver/orca-clouddriver.gradle
#	orca/orca-retrofit/orca-retrofit.gradle

* fix(retrofit): resolve merge conflicts

* chore(clouddriver): remove retrofit2 dependencies

as they're not used in the release-2025.0.x branch.

---------

Co-authored-by: Kiran Godishala <53332225+kirangodishala@users.noreply.github.com>
Co-authored-by: kirangodishala <kiran@opsmx.io>
Co-authored-by: David Byron <dbyron@salesforce.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>