chore(ci): give gradle more memory (#2030)
to try to avoid errors like:

ApplicationControllerTests initializationError FAILED

  org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [org.springframework.test.web.servlet.MockMvc arg0] in constructor [public com.netflix.spinnaker.keel.rest.ApplicationControllerTests(org.springframework.test.web.servlet.MockMvc,com.fasterxml.jackson.databind.ObjectMapper)]: Failed to load ApplicationContext

  Caused by: java.lang.IllegalStateException: Failed to load ApplicationContext

  Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [springfox.documentation.swagger2.configuration.Swagger2DocumentationConfiguration]; nested exception is java.lang.OutOfMemoryError: Java heap space

  Caused by: java.lang.OutOfMemoryError: Java heap space

from https://github.com/spinnaker/keel/runs/6115232379?check_suite_focus=true