chore(dependencies): upgrade to Spring Boot 3.1.12 and align dependent libraries (#7338)
* chore(dependency): upgrade spring boot from 3.0.13 to 3.1.12

* chore(httpclient): explicitly pin Apache HttpClient dependencies
Done this change as part of springboot 3.1.12 upgrade.
Spring Boot 3.1 removed dependency management for Apache HttpClient 4.x.
This caused unresolved artifacts (httpclient, httpmime) during build in
modules such as kork-artifacts and clouddriver-google.

Explicitly pinning compatible HttpClient versions to restore build stability.

Stacktrace:
```
=======================================================
* What went wrong:
Could not determine the dependencies of task ':kork:kork-artifacts:compileJava'.
> Could not resolve all task dependencies for configuration ':kork:kork-artifacts:compileClasspath'.
   > Could not find org.apache.httpcomponents:httpclient:.
     Required by:
         project :kork:kork-artifacts
=========================================================

* What went wrong:
Could not determine the dependencies of task ':clouddriver:clouddriver-google:test'.
> Could not resolve all task dependencies for configuration ':clouddriver:clouddriver-google:testRuntimeClasspath'.
   > Could not find org.apache.httpcomponents:httpmime:.
================================================================
* What went wrong:
Could not determine the dependencies of task ':clouddriver:clouddriver-huaweicloud:test'.
> Could not resolve all task dependencies for configuration ':clouddriver:clouddriver-huaweicloud:testRuntimeClasspath'.
   > Could not find org.apache.httpcomponents:httpmime:.
     Required by:
         project :clouddriver:clouddriver-huaweicloud
```
Reference:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes#dependency-management-for-apache-httpclient-4

* chore(mockito): remove mockito-inline dependency after Spring Boot 3.1.12 upgrade

Spring Boot 3.1 no longer manages the version for mockito-inline via its BOM.
As part of the 3.1.12 upgrade, the mockito-inline dependency caused unresolved
artifact errors in multiple modules (kork-docker, clouddriver-google, kayenta-stackdriver).
Since inline mocking is no longer required, the dependency has been removed.

References:
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes#mockito-5
- https://docs.spring.io/spring-boot/docs/3.1.x/reference/html/dependency-versions.html
- https://github.com/mockito/mockito/releases/tag/v5.0.0
- https://docs.spring.io/spring-boot/docs/3.0.x/reference/html/dependency-versions.html

Stacktrace:
```
* What went wrong:
Could not determine the dependencies of task ':kork:kork-docker:test'.
> Could not resolve all task dependencies for configuration ':kork:kork-docker:testRuntimeClasspath'.
   > Could not find org.mockito:mockito-inline:.
     Required by:
         project :kork:kork-docker
=========================================================
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.mockito:mockito-inline:.
Required by:
    project :kayenta:kayenta-stackdriver
=====================================================
* What went wrong:
Could not determine the dependencies of task ':clouddriver:clouddriver-google:test'.
> Could not resolve all task dependencies for configuration
   > Could not find org.mockito:mockito-inline:.
     Required by:
         project :clouddriver:clouddriver-google
==============================================

* test(sns): fix NPE in TemporarySQSQueueTest after Mockito 5 upgrade

Mockito 5 (upgraded via Spring Boot 3.1) enforces stricter behavior for unstubbed interface methods.
Previously, under Mockito 4, calls like `paginator.topics()` could return a lenient mock or default iterable,
but now they return null unless explicitly stubbed.

The AWS SDK version (2.23.7) remains unchanged, but the stricter mocking caused
a NullPointerException when `topics().stream()` was invoked on a null mock.

Explicitly mocking `paginator.topics()` resolves the issue and aligns the test with
the current AWS SDK paginator API.

Error:
```
TemporarySQSQueueTest > shouldCreateAndTeardownTemporarySqsQueue() FAILED
    java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.core.pagination.sync.SdkIterable.stream()" because the return value of "software.amazon.awssdk.services.sns.paginators.ListTopicsIterable.topics()" is null
        at com.netflix.spinnaker.front50.model.TemporarySQSQueue.getSnsTopicArn(TemporarySQSQueue.java:146)
        at com.netflix.spinnaker.front50.model.TemporarySQSQueue.<init>(TemporarySQSQueue.java:71)
        at com.netflix.spinnaker.front50.model.TemporarySQSQueueTest.shouldCreateAndTeardownTemporarySqsQueue(TemporarySQSQueueTest.java:77)
```

Reference:
- https://github.com/mockito/mockito/releases/tag/v5.0.0
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes#mockito-5

* chore(apache http): Unpinned apache httpclient 4 as the main is already running on http5.

* fix(http5): Correct imports as per apache http5.

Error:
```
spinnaker/kork/kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/EmbeddedArtifactSerializerTest.java:34: error: package org.apache.commons.codec.binary does not exist
import org.apache.commons.codec.binary.Base64;
                                      ^
1 error

> Task :kork:kork-artifacts:compileTestJava

> Task :kork:kork-artifacts:compileTestJava FAILED
```

* fix(kork/artifacts/test): keep up with new mocking convention in mockito 5

to remove this failure:
```
DeserializerHookRegistryTest > testExpansion(String, Object) > com.netflix.spinnaker.kork.artifacts.artifactstore.entities.DeserializerHookRegistryTest.testExpansion(String, Object)[4] FAILED
  com.fasterxml.jackson.databind.JsonMappingException at DeserializerHookRegistryTest.java:181
  Caused by: java.lang.NullPointerException at DeserializerHookRegistryTest.java:181
```
with stack trace:
```
com.fasterxml.jackson.databind.JsonMappingException: Cannot invoke "com.netflix.spinnaker.kork.artifacts.model.Artifact.getReference()" because "artifact" is null (through reference chain: java.util.LinkedHashMap["manifests"])
	at app//com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at app//com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at app//com.fasterxml.jackson.databind.deser.std.ContainerDeserializerBase.wrapAndThrow(ContainerDeserializerBase.java:190)
	at app//com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:638)
	at app//com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:449)
	at app//com.netflix.spinnaker.kork.artifacts.artifactstore.entities.MapDeserializerHook.deserialize(MapDeserializerHook.java:54)
	at app//com.netflix.spinnaker.kork.artifacts.artifactstore.entities.MapDeserializerHook.deserialize(MapDeserializerHook.java:38)
	at app//com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer.deserialize(StdDelegatingDeserializer.java:151)
	at app//com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at app//com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at app//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at app//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at app//com.netflix.spinnaker.kork.artifacts.artifactstore.entities.DeserializerHookRegistryTest.testExpansion(DeserializerHookRegistryTest.java:181)
...
Caused by: java.lang.NullPointerException: Cannot invoke "com.netflix.spinnaker.kork.artifacts.model.Artifact.getReference()" because "artifact" is null
	at com.netflix.spinnaker.kork.artifacts.artifactstore.entities.ExpandToMapHandler.handle(ExpandToMapHandler.java:41)
	at com.netflix.spinnaker.kork.artifacts.artifactstore.entities.MapDeserializerHook.visit(MapDeserializerHook.java:76)
	at com.netflix.spinnaker.kork.artifacts.artifactstore.entities.MapDeserializerHook.deserialize(MapDeserializerHook.java:55)
	at com.netflix.spinnaker.kork.artifacts.artifactstore.entities.MapDeserializerHook.deserialize(MapDeserializerHook.java:38)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializer.java:444)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:623)
```
See
https://github.com/mockito/mockito/wiki/Draft-Mockito-5-release-notes#what-is-the-effect-of-this-new-method.

ExpandToMapHandler calls ArtifactStore.get with no ArtifactDecorators, so update the mock to
that in the mockito 5 way.

* chore(deps): use version 2.15.4 of jackson to match spring boot 3.1.12

* docs(deps): update comments about snakeyaml version

to match spring boot 3.1.12

* chore(deps): unpin logback 1.4.14

since springboot 3.1.12 brings it logback 1.4.14 by itself.

No change to resulting dependencies in e.g.
```
$ ./gradlew orca:orca-web:dependencies
```

* chore(deps): use version 10.1.52 of tomcat

to reduce CVE exposure

* chore(deps): unpin junit-bom:5.9.0

since spring boot 3.1.12 brings in 5.9.3.  We may as well get a slightly newer version,
and have one less dependency to manage.

* fix(clouddriver/test): use a dynamic port for wiremock in OortServiceTest

to avoid these errors:
```
> Task :orca:orca-clouddriver:test
OortServiceTest > verifyCloudFormationStackApi() FAILED
    com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8080
        at app//com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:157)
        at app//com.netflix.spinnaker.orca.clouddriver.OortServiceTest.setUp(OortServiceTest.java:44)

        Caused by:
        java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8080
            at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:220)
            at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:155)
            ... 1 more

            Caused by:
            java.io.IOException: Failed to bind to /0.0.0.0:8080
                at wiremock.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
                at wiremock.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
                at wiremock.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
                at wiremock.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
                at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
                at wiremock.org.eclipse.jetty.server.Server.doStart(Server.java:401)
                at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
                at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:218)
                ... 2 more

                Caused by:
                java.net.BindException: Address already in use
                    at java.base/sun.nio.ch.Net.bind0(Native Method)
                    at java.base/sun.nio.ch.Net.bind(Net.java:555)
                    at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
                    at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
                    at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
                    at wiremock.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
                    ... 9 more

OortServiceTest > getServerGroupFromClusterPathMustNotComeAfterQuery() FAILED
    com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8080
        at app//com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:157)
        at app//com.netflix.spinnaker.orca.clouddriver.OortServiceTest.setUp(OortServiceTest.java:44)

        Caused by:
        java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8080
            at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:220)
            at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:155)
            ... 1 more

            Caused by:
            java.io.IOException: Failed to bind to /0.0.0.0:8080
                at wiremock.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
                at wiremock.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
                at wiremock.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
                at wiremock.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
                at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
                at wiremock.org.eclipse.jetty.server.Server.doStart(Server.java:401)
                at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
                at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:218)
                ... 2 more

                Caused by:
                java.net.BindException: Address already in use
                    at java.base/sun.nio.ch.Net.bind0(Native Method)
                    at java.base/sun.nio.ch.Net.bind(Net.java:555)
                    at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
                    at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
                    at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
                    at wiremock.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
                    ... 9 more

```

---------

Co-authored-by: David Byron <dbyron@salesforce.com>