fix(httpclient): upgrade to Apache HttpClient 5 to resolve missing class error
Build was failing due to missing org.apache.hc.client5.http.classic.HttpClient
when using HttpComponentsClientHttpRequestFactory. Updated dependencies and
RestTemplate configuration to use HttpClient 5 as recommended for Spring Boot 3.

Error:

```
> Task :gate:gate-web:compileTestJava FAILED
spinnaker/gate/gate-web/src/test/java/com/netflix/spinnaker/gate/security/oauth/config/OAuth2TestConfiguration.java:76: error: cannot access HttpClient
        new HttpComponentsClientHttpRequestFactory(client);
        ^
  class file for org.apache.hc.client5.http.classic.HttpClient not found
1 error

FAILURE: Build failed with an exception.
```

Also, put back the previous assertions in AuthConfigTest.java class
Reference:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#apache-httpclient-in-resttemplate