Fix orca bakery (#4370)
* fix(bakery): restore groovy-datetime to the classpath to prevent an exception

Prior to https://github.com/spinnaker/kork/pull/1001 and https://github.com/spinnaker/orca/pull/4364, org.codehaus.groovy:groovy-all was on the classpath.  groovy-all brings in many transitive dependencies, including org.codehaus.groovy:groovy-datetime.  Without groovy-datetime, some bake stages fail with this exception:

groovy.lang.MissingMethodException: No signature of method: java.time.ZonedDateTime.format() is applicable for argument types: (String) values: [yyyyMMddHHmmss]
Possible solutions: format(java.time.format.DateTimeFormatter), from(java.time.temporal.TemporalAccessor), getAt(java.lang.String), print(java.lang.Object), print(java.io.PrintWriter)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at com.netflix.spinnaker.orca.bakery.pipeline.BakeStage.parallelContexts(BakeStage.groovy:118)

* chore(remote-stage): stop applying gradle/spock.gradle since there are no spock tests in this module

* chore(kotlin): provide org.junit.jupiter:junit-jupiter-engine as a test runtime dependency in gradle/kotlin.gradle

so e.g. JUnit5Minutests run.  See https://github.com/dmcg/minutest/blob/master/docs/installation.md#installation.

Up to now, if those tests run, it's because junit-jupiter-engine has been coming in some
other way, but now it's explicit.

* chore(dependencies): remove groovy-all from test classpath

to ensure that, at least where we have test coverage, tests don't pass because groovy-all
is present.  In other words, try to ensure that we don't have shipping code that depends
on groovy-all.  It's still possible that we do since test coverage is never 100%, but this
is progress.