fix(tests): Update spring profile property
As part of springboot 3.0.13 upgrade, faced below failures due to a property change

Error:

```
com.netflix.spinnaker.clouddriver.aws.test.ModifyServerGroupLaunchTemplateSpec ✘ Given request to update launch template, successfully submit update auto scaling group request with expected configuration.

    java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@1d0e2c96 testClass = com.netflix.spinnaker.clouddriver.aws.test.ModifyServerGroupLaunchTemplateSpec, locations = [], classes = [com.netflix.spinnaker.clouddriver.Main], contextInitializerClasses = [], activeProfiles = ["launch-templates"], propertySourceLocations = [], propertySourceProperties = ["spring.config.location = classpath:clouddriver.yml", "org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true", "server.port=0"], contextCustomizers = [org.spockframework.spring.mock.SpockContextCustomizer@0, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@1f, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizer@4d6ccc97, [ImportsContextCustomizer@7fa498b3 key = [com.netflix.spinnaker.clouddriver.aws.AwsTestConfiguration]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@3ddeaa5f, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@795f8317, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@4ccc3fa5, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@1d6d1d42, org.springframework.boot.test.web.reactive.server.WebTestClientContextCustomizer@5afbd567, org.springframework.boot.test.context.SpringBootTestAnnotation@240f904f], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]

    Caused by: org.springframework.boot.context.config.InvalidConfigDataPropertyException: Property 'spring.profiles' imported from location 'class path resource [clouddriver.yml]' is invalid and should be replaced with 'spring.config.activate.on-profile' [origin: class path resource [clouddriver.yml] - 43:13]
 ```

Reference Doc:

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide#profile-specific-documents