chore(dependencies): Autobump korkVersion (#6082)
* chore(dependencies): Autobump korkVersion

* refactor(appengine): remove isDisabled() method with groovy 3 upgrade

While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encounter below error in clouddriver-appengine module as groovy 3 is smart enough to create implicit getter with name isDisabled() for `disabled` boolean property.

```
/clouddriver/clouddriver-appengine/build/tmp/compileGroovy/groovy-java-stubs/com/netflix/spinnaker/clouddriver/appengine/model/AppengineServerGroup.java:65: error: method isDisabled() is already defined in class AppengineServerGroup
@java.lang.Override() public  java.lang.Boolean isDisabled() { return (java.lang.Boolean)null;}
                                                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /clouddriver/clouddriver-appengine/src/main/java/com/netflix/spinnaker/clouddriver/appengine/config/AppengineCredentialsConfiguration.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
startup failed:
Compilation failed; see the compiler error output for details.
1 error
> Task :clouddriver-appengine:compileGroovy FAILED
```
To fix this issue removed `isDisabled()` method.

* refactor(oracle): remove isDisabled() method with groovy 3 upgrade

While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encounter below error in clouddriver-oracle module as groovy 3 is smart enough to create implicit getter with name isDisabled() for `disabled` boolean property.
```
startup failed:
/clouddriver/clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/model/OracleServerGroup.groovy: 76: Repetitive method name/signature for method 'java.lang.Boolean isDisabled()' in class 'com.netflix.spinnaker.clouddriver.oracle.model.OracleServerGroup$View'.
 @ line 76, column 5.
       @Override
       ^
/clouddriver/clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/model/OracleServerGroup.groovy: -1: Repetitive method name/signature for method 'java.lang.Boolean isDisabled()' in class 'com.netflix.spinnaker.clouddriver.oracle.model.OracleServerGroup$View'.
 @ line -1, column -1.
2 errors
> Task :clouddriver-oracle:compileGroovy FAILED

```
To fix this issue removed `isDisabled()` method.

* refactor(core/test): remove isDisabled() method with groovy 3 upgrade

While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encounter below error in clouddriver-core module as groovy 3 is smart enough to create implicit getter with name isDisabled() for `disabled` boolean property.

```
> Task :clouddriver-core:compileTestGroovy FAILED
startup failed:
/clouddriver/clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/model/SimpleServerGroup.groovy: 37: Repetitive method name/signature for method 'java.lang.Boolean isDisabled()' in class 'com.netflix.spinnaker.clouddriver.model.SimpleServerGroup'.
 @ line 37, column 3.
     @Override
     ^
/clouddriver/clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/model/SimpleServerGroup.groovy: -1: Repetitive method name/signature for method 'java.lang.Boolean isDisabled()' in class 'com.netflix.spinnaker.clouddriver.model.SimpleServerGroup'.
 @ line -1, column -1.
2 errors
```
To fix this issue removed `isDisabled()` method.

* refactor(google): remove isDisabled() method with groovy 3 upgrade

While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encounter below error in clouddriver-google module as groovy 3 is smart enough to create implicit getter with name isDisabled() for `disabled` boolean property.
```
/clouddriver/clouddriver-google/build/tmp/compileGroovy/groovy-java-stubs/com/netflix/spinnaker/clouddriver/google/model/GoogleServerGroup.java:167: error: method isDisabled() is already defined in class GoogleServerGroup.View
@java.lang.Override() public  java.lang.Boolean isDisabled() { return (java.lang.Boolean)null;}
```
To fix this issue removed `isDisabled()` method.

* refactor(aws/test): remove isDisabled() method with groovy 3 upgrade

While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encounter below error in clouddriver-aws module as groovy 3 is smart enough to create implicit getter with name isDisabled() for `disabled` boolean property.

```
startup failed:
/clouddriver/clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/SimpleServerGroup.groovy: 40: Repetitive method name/signature for method 'java.lang.Boolean isDisabled()' in class 'com.netflix.spinnaker.clouddriver.aws.deploy.asg.SimpleServerGroup'.
 @ line 40, column 3.
     @Override
     ^
/clouddriver/clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/asg/SimpleServerGroup.groovy: -1: Repetitive method name/signature for method 'java.lang.Boolean isDisabled()' in class 'com.netflix.spinnaker.clouddriver.aws.deploy.asg.SimpleServerGroup'.
 @ line -1, column -1.
2 errors
> Task :clouddriver-aws:compileTestGroovy FAILED
```

```
startup failed:
/clouddriver/clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/DiscoverySupportUnitSpec.groovy: 573: Repetitive method name/signature for method 'java.lang.Boolean isDisabled()' in class 'com.netflix.spinnaker.clouddriver.aws.deploy.ops.discovery.DiscoverySupportUnitSpec$DefaultServerGroup'.
 @ line 573, column 5.
       Boolean isDisabled() {disabled}
       ^
/clouddriver/clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/DiscoverySupportUnitSpec.groovy: -1: Repetitive method name/signature for method 'java.lang.Boolean isDisabled()' in class 'com.netflix.spinnaker.clouddriver.aws.deploy.ops.discovery.DiscoverySupportUnitSpec$DefaultServerGroup'.
 @ line -1, column -1.
2 errors
> Task :clouddriver-aws:compileTestGroovy FAILED
```
To fix this issue removed `isDisabled()` method.

* refactor(test): add runtime jupiter engine and remove vintage engine with upgrade of groovy 3

---------

Co-authored-by: root <root@0c89bc74b80c>
Co-authored-by: j-sandy <30489233+j-sandy@users.noreply.github.com>