refactor(eureka): Unping eureka dependency to get updated version of it transitively from spring cloud libraries.
```

> Task :kork:kork-eureka:compileJava FAILED
spinnaker/kork/kork-eureka/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaAutoConfiguration.java:56: error: no suitable constructor found for DiscoveryClient(ApplicationInfoManager,EurekaClientConfig,TransportClientFactories)
    return new DiscoveryClient(
           ^
    constructor DiscoveryClient.DiscoveryClient(InstanceInfo,EurekaClientConfig,DiscoveryClientOptionalArgs) is not applicable
      (argument mismatch; ApplicationInfoManager cannot be converted to InstanceInfo)
    constructor DiscoveryClient.DiscoveryClient(InstanceInfo,EurekaClientConfig,AbstractDiscoveryClientOptionalArgs) is not applicable
      (argument mismatch; ApplicationInfoManager cannot be converted to InstanceInfo)
    constructor DiscoveryClient.DiscoveryClient(ApplicationInfoManager,EurekaClientConfig,DiscoveryClientOptionalArgs) is not applicable
      (argument mismatch; TransportClientFactories cannot be converted to DiscoveryClientOptionalArgs)
    constructor DiscoveryClient.DiscoveryClient(ApplicationInfoManager,EurekaClientConfig,AbstractDiscoveryClientOptionalArgs) is not applicable
      (argument mismatch; TransportClientFactories cannot be converted to AbstractDiscoveryClientOptionalArgs)
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
```

Spring cloud upgrade from 2021.0.x to 2022.0.x also upgrades the eureka client transitively from [1.10.17](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies/2021.0.8) to [2.0.1](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies/2022.0.5)
Eureka client 2.0.x is not backward compatible with 1.0.x. The constructor has also introduced new parameter.