refactor(dependency): replace rxjava with rxjava3 during upgrade of spring boot 3.0.x
While upgrading the spring boot to 3.0.13 and spring cloud 2022.0.5, encountered the below errors during build process of orca:
```
spinnaker/orca/orca-web/src/test/java/com/netflix/spinnaker/orca/controllers/ProjectControllerTest.java:27: error: package rx does not exist

import rx.Observable;
> Task :orca:orca-web:compileTestJava FAILED
         ^
spinnaker/orca/orca-web/src/test/java/com/netflix/spinnaker/orca/controllers/ProjectControllerTest.java:96: error: cannot find symbol
        .thenReturn(Observable.from(Collections.singletonList(execution1)));
                    ^
  symbol:   variable Observable
  location: class ProjectControllerTest
spinnaker/orca/orca-web/src/test/java/com/netflix/spinnaker/orca/controllers/ProjectControllerTest.java:98: error: cannot find symbol
        .thenReturn(Observable.from(Collections.singletonList(execution2)));
                    ^
  symbol:   variable Observable
  location: class ProjectControllerTest
3 errors
```
Spring boot 3.x deprecated and removed rxjava, and rxjava3 has been added. So, update the imports.
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#rxjava