fix(clouddriver/aws): align CredentialsParser types in AmazonCredentialsInitializer (#7207) (#7208)
* test(clouddriver/aws): demonstrate behavior of AmazonCredentialsInitializer

specifically, that it fails to produce the kind of CredentialsParser bean that amazonCredentialsLoader requires.

* fix(clouddriver/aws): align CredentialsParser types in AmazonCredentialsInitializer

With this change, the amazonCredentialsParser method provides the type of CredentialsParser that amazonCredentialsLoader expects.

For the curious, without the cast, there's a compiler error:

/Users/dbyron/src/spinnaker/spinnaker/clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsInitializer.java:84: error: incompatible types: cannot infer type arguments for AmazonCredentialsParser<>
    return new AmazonCredentialsParser<>(
                                      ^
    reason: inference variable V has incompatible equality constraints NetflixAmazonCredentials,CAP#1
  where V is a type-variable:
    V extends NetflixAmazonCredentials declared in class AmazonCredentialsParser
  where CAP#1 is a fresh type-variable:
    CAP#1 extends NetflixAmazonCredentials from capture of ? extends NetflixAmazonCredentials

(cherry picked from commit 57b5928f5b52e10f20ad29cdfdeb57b96dd22614)

Co-authored-by: David Byron <82477955+dbyron-sf@users.noreply.github.com>