fix(resilience4j): align to Spring Boot 3 – upgrade to v2.3.0
Spring Boot 3 auto‑config relies on Resilience4j ≥ 2.0.1, which
introduces `resilience4j‑spring‑boot3` and new factory methods such as
`RetryRegistry.of(Map, RegistryEventConsumer, Map)`.  Our build was
pinned to 1.5.0, causing `NoSuchMethodError` at runtime.

Error:
```
> Task :keel:keel-core:compileKotlin
e: spinnaker/keel/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PersistenceRetry.kt: (9, 11): Unresolved reference: vavr
e: spinnaker/keel/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PersistenceRetry.kt: (47, 7): Unresolved reference: Try
```

The root cause of this issue is removal of `io.vavr` dependency from resilience4j:2.0.2.
https://github.com/resilience4j/resilience4j/releases/tag/v2.0.0
Resilience4j comes as transitive dependency of spring-cloud-dependencies.
https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies/2022.0.5