Refactor(rxjava3): migrate codebase to use RxJava3
Updated the code to use RxJava3 instead of RxJava. In Spring Boot 2, RxJava was included as a transitive dependency. As part of the upgrade to Spring Boot 3, RxJava was removed, and RxJava3 has been adopted to ensure compatibility with the updated framework.

Error:
```
> Task :kayenta-web:compileJava FAILED
kayenta/kayenta-web/src/main/java/com/netflix/kayenta/controllers/CanaryController.java:225: error: cannot find symbol
            .toBlocking()
            ^
  symbol:   method toBlocking()
  location: class Single<List<PipelineExecution>>

1 error
```
References:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#rxjava