refactor(redis): remove reflection usage for internalPool access
The `internalPool` property was removed from JedisPool, so reflection logic was eliminated.
Since `JedisPool` extends `Pool<Jedis>`, the JedisPool bean is now directly used as a `Pool<Jedis>`.

```

groovy.lang.MissingPropertyException: No such property: internalPool for class: redis.clients.jedis.JedisPool
  at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:67) ~[groovy-4.0.15.jar:4.0.15]
  at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:163) ~[groovy-4.0.15.jar:4.0.15]
  at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) ~[groovy-4.0.15.jar:4.0.15]
  at com.netflix.spinnaker.rosco.persistence.config.JedisConfig$1.health(JedisConfig.groovy:62) ~[rosco-core.jar:na]
  at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37) ~[spring-boot-actuator-3.0.13.jar:3.0.13]
  at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:94) ~[spring-boot-actuator-3.0.13.jar:3.0.13]
  at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:47) ~[spring-boot-actuator-3.0.13.jar:3.0.13]
  at org.springframework.boot.actuate.health.HealthEndpointSupport.getLoggedHealth(HealthEndpointSupport.java:172) ~[spring-boot-actuator-3.0.13.jar:3.0.13]

```