fix(gate/api-tck/test): remove noisy startup errors from GateFixtureTest output (#7572)
Mock beans and disable features that produce spurious errors and log messages during the
gate-api-tck test. These fire because the Spring context starts background tasks that try
to reach downstream services that aren't running in the test environment.

Mocked beans and the errors they prevent:
```
  DownstreamServicesHealthIndicator:
    ERROR DownstreamServicesHealthIndicator : Exception received during
      health check of service: clouddriver, java.net.ConnectException:
      Failed to connect to localhost/[0:0:0:0:0:0:0:1]:7002

  ApplicationService:
    ERROR ApplicationService : Falling back to application cache
      SpinnakerNetworkException: java.net.ConnectException: Failed to
      connect to localhost/[0:0:0:0:0:0:0:1]:7002

  DefaultProviderLookupService:
    ERROR DefaultProviderLookupService : Unable to refresh account
      details cache
      SpinnakerNetworkException: java.net.ConnectException: Failed to
      connect to localhost/[0:0:0:0:0:0:0:1]:7002
```
Disabled properties and the messages they prevent:
```
  spinnaker.extensibility.remote-plugins.enabled=false:
    INFO RemotePluginInfoReleaseCache : Cached 0 remote plugin configurations.

  spinnaker.extensibility.deck-proxy.enabled=false:
    INFO DeckPluginCache : Cached 0 deck plugins
```

Make the changes in GateFixtureTest instead of GateFixture in case there are
implementations of GateFixture outside the Spinnaker codebase that depend on these
beans/features being enabled.