fix(artifacts): references containing '+' break matching (#1113)
* fix(artifacts): references containing '+' break matching (#1496)

When expected artifact does matching on a base64 reference, containing
special regex characters, it will attempt pattern matching where ‘+’
actually means something in regex and will fail matches because of this.
This commit ensures that all base64 characters can be matched against
that may not be valid regex expression.

Example pipeline:

```json
{
  "application" : "spinnaker-ci",
  "description" : "This pipeline ensures that artifacts with regex characters like '+' succeed in pipelines.",
  "expectedArtifacts" : [ {
    "defaultArtifact" : {
      "artifactAccount" : "embedded-artifact",
      "id" : "f435c890-c5b6-4bdb-a733-d788413fd5c1",
      "type" : "embedded/base64"
    },
    "displayName" : "regex-artifact",
    "id" : "be22c2c5-6561-4f41-b885-367ef91b8362",
    "matchArtifact" : {
      "artifactAccount" : "embedded-artifact",
      "id" : "cf4891ff-6e56-495b-a41e-46f120783ff8",
      "name" : "match-artifact",
      "reference" : "+++",
      "type" : "embedded/base64"
    },
    "useDefaultArtifact" : false,
    "usePriorArtifact" : false
  } ],
  "id" : "8ed4f44b-a072-37e0-88b5-61a63c5668a9",
  "keepWaitingPipelines" : false,
  "limitConcurrent" : true,
  "name" : "Webhook Trigger Base64 Regex",
  "stages" : [ {
    "completeOtherBranchesThenFail" : false,
    "continuePipeline" : false,
    "expectedArtifacts" : [ {
      "defaultArtifact" : {
        "artifactAccount" : "embedded-artifact",
        "id" : "f435c890-c5b6-4bdb-a733-d788413fd5c1",
        "type" : "embedded/base64"
      },
      "displayName" : "regex-artifact",
      "id" : "be22c2c5-6561-4f41-b885-367ef91b8362",
      "matchArtifact" : {
        "artifactAccount" : "embedded-artifact",
        "id" : "cf4891ff-6e56-495b-a41e-46f120783ff8",
        "name" : "match-artifact",
        "reference" : "+++",
        "type" : "embedded/base64"
      },
      "useDefaultArtifact" : false,
      "usePriorArtifact" : false
    } ],
    "failPipeline" : true,
    "inputArtifacts" : [ {
      "account" : "embedded-artifact",
      "id" : "be22c2c5-6561-4f41-b885-367ef91b8362"
    } ],
    "name" : "Bake (Manifest)",
    "namespace" : "my-namespace",
    "outputName" : "nginx",
    "refId" : "1",
    "requisiteStageRefIds" : [ ],
    "templateRenderer" : "HELM3",
    "type" : "bakeManifest"
  } ],
  "triggers" : [ {
    "enabled" : true,
    "expectedArtifactIds" : [ "be22c2c5-6561-4f41-b885-367ef91b8362" ],
    "id" : "391f8418-3805-406e-82fb-2bb1ea02ff5d",
    "payloadConstraints" : { },
    "source" : "base64-regex-test",
    "type" : "webhook"
  } ]
}
```

curl with
```bash
curl http://localhost:8084/webhooks/webhook/base64-regex-test -d '{"artifacts":[{"artifactAccount":"embedded-artifact","name":"match-artifact","reference":"+++","type":"embedded/base64"}],"expectedArtifactIds":["be22c2c5-6561-4f41-b885-367ef91b8362"],"expectedArtifacts":[{"defaultArtifact":{"artifactAccount":"embedded-artifact","id":"f435c890-c5b6-4bdb-a733-d788413fd5c1","type":"embedded/base64"},"displayName":"regex-artifact","id":"be22c2c5-6561-4f41-b885-367ef91b8362","matchArtifact":{"artifactAccount":"embedded-artifact","id":"cf4891ff-6e56-495b-a41e-46f120783ff8","name":"match-artifact","reference":"+++","type":"embedded/base64"},"useDefaultArtifact":false,"usePriorArtifact":false}]}
```

echo will log this exception
```
java.util.regex.PatternSyntaxException: Dangling meta character '+' near index 0
```

This commit addresses this error by instead doing a simple string comparison
and if that fails, then we do the regex.

Signed-off-by: benjamin-j-powell <bjp@apple.com>

* fixup! fix(artifacts): references containing '+' break matching (#1496)

Signed-off-by: benjamin-j-powell <bjp@apple.com>

---------

Signed-off-by: benjamin-j-powell <bjp@apple.com>
Co-authored-by: Benevolent Benjamin Powell <benjamin_j_powell@apple.com>
Co-authored-by: benjamin-j-powell <bjp@apple.com>