chore(dependencies): Autobump korkVersion (#6157)
* chore(dependencies): Autobump korkVersion

* chore(build): use --no-daemon for ecs integration tests

since it seems to resolve hanging/out of memory errors when running locally

* chore(build): increase the stack size to try to fix build failures

*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 830

see https://stackoverflow.com/questions/60526670/what-is-the-meaning-cause-of-java-lang-instrument-assertion-failed-er

* chore(build): try a bigger stack

since the builds (e.g. https://github.com/spinnaker/clouddriver/actions/runs/8015292221/job/21914062873) keep failing.

> Task :clouddriver-ecs:integrationTest
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 830
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "mysql-cj-abandoned-connection-cleanup"

---------

Co-authored-by: root <root@91023be377be>
Co-authored-by: David Byron <dbyron@salesforce.com>