refactor(web/test): remove hard-coded port numbers from EchoServiceTest (#1828)
* refactor(web/test): remove hard-coded port numbers from EchoServiceTest

so the test can pass when these ports are in-use:

EchoServiceTest > initializationError FAILED
    java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.Net.bind(Net.java:544)
        at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:648)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:393)
        at com.squareup.okhttp.mockwebserver.MockWebServer.start(MockWebServer.java:354)
        at com.squareup.okhttp.mockwebserver.MockWebServer.start(MockWebServer.java:337)
        at com.squareup.okhttp.mockwebserver.MockWebServer.start(MockWebServer.java:324)
        at com.netflix.spinnaker.gate.service.EchoServiceTest.setUp(EchoServiceTest.java:57)

While we're at it, also convert from
junit4 which com.squareup.okhttp.mockwebserver.MockWebServer uses, to junit5, which
wiremock uses.

* chore(build): give tests more memory to execute

to avoid OutOfMemoryErrors
 Please enter the commit message for your changes. Lines starting