chore(dependencies): Autobump korkVersion (#1804)
* chore(dependencies): Autobump korkVersion

* chore(dependency): pin graphql-java to avoid version bump during upgrade to spring boot 2.7.x

In spring boot 2.7.x, support for spring-graphql project has been introduced with a new starter `spring-boot-starter-graphql`.

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#new-spring-graphql-starter

Spring boot 2.7.x bring `com.graphql-java:graphql-java:18.5` as its transitive dependency.

https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.18/spring-boot-dependencies-2.7.18.pom

Since the existing `com.graphql-java-kickstart:graphql-spring-boot-starter:7.0.1` and `com.graphql-java-kickstart:graphql-java-tools:6.0.2` uses graphql-java:14.0, pinning the graphql-java version to 14.0 till the adoption of new spring-graphql-starter.

* refactor(test): add EmbeddedRedis to get connection pool for test execution during upgrade to spring boot 2.7.x

While upgrading spring boot 2.7.18, encounter below error during test compilation of gate-web module:
```
Unexpected exception thrown: java.lang.AssertionError:
Expecting:
 <Unstarted application context org.springframework.boot.test.context.assertj.AssertableApplicationContext[startupFailure=org.springframework.context.ApplicationContextException]>
to get beans of type:
 <org.springframework.session.data.redis.config.ConfigureRedisAction>:
but context failed to start:
 org.springframework.context.ApplicationContextException: Failed to start bean 'springSessionRedisMessageListenerContainer'; nested exception is org.springframework.data.redis.listener.adapter.RedisListenerExecutionFailedException: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
```
The `com.netflix.spinnaker.gate.config.RedisConfigTest.testCircularDependenciesException` and `com.netflix.spinnaker.gate.config.RedisConfigTest.testCircularDependenciesExceptionSecure` tests generated the above error. The root cause is unavailability of redis resource pool. So, adding EmbeddedRedis to provide resource pool during test execution.

---------

Co-authored-by: root <root@51dce6428a99>
Co-authored-by: j-sandy <30489233+j-sandy@users.noreply.github.com>