refactor(test): replace deprecated mockito class Matchers with ArgumentMatchers and its methods during upgrade to spring boot 2.6.x (#6128)
While upgrading spring boot 2.6.15, encounter similar errors as given below in multiple module of clouddriver (clouddriver-google, clouddriver-cloudfoundry, clouddriver-ecs) during test compilation:
```
> Task :clouddriver-google:compileTestGroovy FAILED
/clouddriver/clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/SetStatefulDiskAtomicOperationConverterTest.java:20: error: cannot find symbol
import static org.mockito.Matchers.any;
                         ^
  symbol:   class Matchers
  location: package org.mockito
/clouddriver/clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/SetStatefulDiskAtomicOperationConverterTest.java:20: error: static import only from classes and interfaces
import static org.mockito.Matchers.any;
^
Note: /clouddriver/clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/SetStatefulDiskDescriptionValidatorTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
```
Spring boot [2.6.15](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.6.15/spring-boot-dependencies-2.6.15.pom) brings mockito 4.0.0 as transitive dependency. The `Matchers` was deprecated in 3.x and now it is removed from mockito [4.0.0](https://github.com/mockito/mockito/releases/tag/v4.0.0).
To fix these issues, replacing `Matchers` with `ArgumentMatchers` and its methods.