refactor(http status code): refactor code to use the unified HTTP status code with spring boot upgrade to 3.x
Upgrade of spring boot 3.0 brings springframework 6.0 as its transitive dependency. Springframework 6.0 has introduced unified HTTP status handling, that caused the below error:
```
> Task :orca-webhook:compileJava
orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.java:130: error: incompatible types: HttpStatusCode cannot be converted to HttpStatus
      if (shouldRetry(statusCode, stageData)) {
                      ^
orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.java:175: error: incompatible types: HttpStatusCode cannot be converted to HttpStatus
    monitor.setStatusCode(response.getStatusCode());
                                                ^
orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/WebhookResponseProcessor.java:85: error: incompatible types: HttpStatusCode cannot be converted to HttpStatus
    webhookOutput.setStatusCode(e.getStatusCode());
                                               ^
orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/WebhookResponseProcessor.java:93: error: incompatible types: HttpStatusCode cannot be converted to HttpStatus
    TaskResult result = processReceivedFailureStatusCode(e.getStatusCode(), webhookOutput);
                                                                        ^
orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/WebhookResponseProcessor.java:165: error: incompatible types: HttpStatusCode cannot be converted to HttpStatus
    webhookOutput.setStatusCode(response.getStatusCode());
                                                      ^
```
In order to fix this issue, refactor the code using `HttpStatusCode` interface implemented by `HttpStatus`.
https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-6.x/d1a3285d5f7658ac716ad4193131102e6f2f50c1#general-web-revision