refactor: Upgrade HttpClient from Apache HttpClient 4.x to 5.x across modules
Springboot 3.1 stops managing dependency for httpClient 4 so upgrading to 5 prior to 3.1 migration.

This change migrates remaining HttpClient 4.x usage to the Apache
HttpComponents 5.x APIs and removes all deprecated / removed classes and
methods. The migration includes the following updates:

• Replaced HttpClientBuilder (4.x) with CloseableHttpClient (5.x) and
  updated configuration to use RequestConfig, HttpClientBuilder, and the
  new fluent API introduced in 5.x.

• Removed ServiceUnavailableRetryStrategy and legacy retry handler API.
  Implemented custom retry logic using HttpRequestRetryStrategy and
  HttpResponseRetryStrategy equivalents in 5.x.

• Replaced LaxRedirectStrategy (4.x) with DefaultRedirectStrategy /
  RedirectSupport in 5.x. Added explicit redirect validation against
  UserConfiguredUrlRestrictions before following Location headers.

• Added safe URI extraction helpers because request.getRequestLine().getUri()
  no longer exists in 5.x. All logging now uses HttpRequest.getRequestUri()
  and guards against IllegalStateException / unknown URIs.

• Updated HttpRequest parsing helper:
      SessionInputBufferImpl buffer = new SessionInputBufferImpl(metrics, size)
      DefaultHttpRequestParser parser = new DefaultHttpRequestParser()
      ClassicHttpRequest request = parser.parse(buffer, inputStream)

Overall this aligns all HTTP networking code to Apache HttpComponents 5.x,
required for Java 17+ compatibility and to remove legacy APIs deprecated
upstream.

Error:
```
Kork:
===============================================
Build:
===============================================
> Task :kork:kork-artifacts:compileJava FAILED
spinnaker/kork/kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStoreStorer.java:30: error: package org.apache.http does not exist
import org.apache.http.HttpStatus;
                      ^
1 error

===============================================

Echo
================================================
> Task :echo:echo-notifications:compileTestGroovy
startup failed:
spinnaker/echo/echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/slack/SlackServiceSpec.groovy: 18: unable to resolve class org.apache.http.NameValuePair
 @ line 18, column 1.
   import org.apache.http.NameValuePair
   ^

spinnaker/echo/echo-notifications/src/test/groovy/com/netflix/spinnaker/echo/slack/SlackServiceSpec.groovy: 19: unable to resolve class org.apache.http.client.utils.URLEncodedUtils
 @ line 19, column 1.
   import org.apache.http.client.utils.URLEncodedUtils

2 errors
=================================================

Orca
================================================
> Task :orca:orca-core:compileJava
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:28: error: package org.apache.http does not exist
import org.apache.http.HttpHost;
                      ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:29: error: package org.apache.http does not exist
import org.apache.http.HttpRequest;
                      ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:30: error: package org.apache.http does not exist
import org.apache.http.HttpResponse;
                      ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:31: error: package org.apache.http does not exist
import org.apache.http.HttpStatus;
                      ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:32: error: package org.apache.http does not exist
import org.apache.http.ProtocolException;
                      ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:33: error: package org.apache.http.client does not exist
import org.apache.http.client.RedirectStrategy;
                             ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:34: error: package org.apache.http.client does not exist
import org.apache.http.client.ServiceUnavailableRetryStrategy;
                             ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:35: error: package org.apache.http.client.config does not exist
import org.apache.http.client.config.RequestConfig;
                                    ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:36: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.CloseableHttpResponse;
                                     ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:37: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.HttpGet;
                                     ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:38: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.HttpUriRequest;
                                     ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:39: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.CloseableHttpClient;
                                  ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:40: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.HttpClientBuilder;
                                  ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:41: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.HttpClients;
                                  ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:42: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.LaxRedirectStrategy;
                                  ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:43: error: package org.apache.http.protocol does not exist
import org.apache.http.protocol.HttpContext;
                               ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:44: error: package org.apache.http.protocol does not exist
import org.apache.http.protocol.HttpCoreContext;
                               ^
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:52: error: cannot find symbol
  private CloseableHttpClient httpClient;
          ^
  symbol:   class CloseableHttpClient
  location: class HttpClientUtils
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:69: error: cannot find symbol
  private CloseableHttpClient create(
          ^
  symbol:   class CloseableHttpClient
  location: class HttpClientUtils
spinnaker/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java:208: error: cannot find symbol
    public RedirectStrategy getLaxRedirectStrategy() {
           ^
  symbol:   class RedirectStrategy
  location: class HttpClientUtils.CustomRedirectStrategy
20 errors

==========================================================

> Task :orca:orca-webhook:compileJava FAILED
spinnaker/orca/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/WebhookStatusCheckUrlRetriever.java:24: error: package org.apache.http does not exist
import org.apache.http.HttpHeaders;
                      ^
1 error

================================================

Clouddriver
====================================================
> Task :clouddriver:clouddriver-google:compileTestGroovy FAILED
spinnaker/clouddriver/clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/StubHttpTransport.java:43: error: package org.apache.http.entity.mime does not exist
import org.apache.http.entity.mime.MultipartEntityBuilder;
                                  ^
spinnaker/clouddriver/clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/StubHttpTransport.java:211: error: cannot find symbol
  private void addResponse(MultipartEntityBuilder multipartResponse, LowLevelHttpResponse response)
                           ^
  symbol:   class MultipartEntityBuilder
  location: class StubHttpTransport
Note: spinnaker/clouddriver/clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/deploy/validators/SetStatefulDiskDescriptionValidatorTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
startup failed:
Compilation failed; see the compiler error output for details.

1 error
=======================================================
```