fix(build): fix the following error: (#1224)
Run BRANCHES=$(git branch -r --contains refs/tags/v7.249.0)
BRANCHES is '  origin/HEAD -> origin/master
  origin/master'
NUM_BRANCHES is '2'
exactly one branch required to release kork, but there are 2 (  origin/HEAD -> origin/master
  origin/master)
Error: Process completed with exit code 1.