refactor(test): refactor the method getType() to getTableType() as part of spring boot 3.x upgrade
```
> Task :kork-sql-test:compileJava FAILED
/kork/kork-sql-test/src/main/java/com/netflix/spinnaker/kork/sql/test/SqlTestUtil.java:278: error: cannot find symbol
                table.getType().isTable()
                               ^
  symbol:   method isTable()
  location: class Class<CAP#1>
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Record from capture of ?
1 error
```
The root cause is the change in method of `org.jooq.Table` class upgrading jooq transitively from 3.14.16 to 3.17.16 while spring boot 2.7.18 to 3.0.13 upgrade.
In order to fix this issue refactoring the `getTableType()` method.