fix(clouddriver/aws): align CredentialsParser types in AmazonCredentialsInitializer
With this change, the amazonCredentialsParser method provides the type of CredentialsParser that amazonCredentialsLoader expects.

For the curious, without the cast, there's a compiler error:

/Users/dbyron/src/spinnaker/spinnaker/clouddriver/clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsInitializer.java:84: error: incompatible types: cannot infer type arguments for AmazonCredentialsParser<>
    return new AmazonCredentialsParser<>(
                                      ^
    reason: inference variable V has incompatible equality constraints NetflixAmazonCredentials,CAP#1
  where V is a type-variable:
    V extends NetflixAmazonCredentials declared in class AmazonCredentialsParser
  where CAP#1 is a fresh type-variable:
    CAP#1 extends NetflixAmazonCredentials from capture of ? extends NetflixAmazonCredentials