feat(clouddriver/aws): support multiple managing accounts (#7187)
* refactor(aws): convert AmazonCredentialsInitializer from groovy to java

with a bonus removal of a star import along the way

* refactor(aws): create an AWSAccountInfoLookup bean to simplify the constructors in the AmazonCredentialsParser class

* feat(aws): support multiple managing accounts

* fix(aws): when using a ProfileCredentialsProvider / managingAccountProfile, provide a region from the profile to aws sdk clients

to prevent error messages like:

com.amazonaws.services.ec2.model.AmazonEC2Exception: AWS was not able to validate the provided access credentials (Service: AmazonEC2; Status Code: 401; Error Code: AuthFailure; Request ID: <request id>)

during DefaultAWSAccountInfoLookup.listRegions

---------

Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>