chore(dependencies): remove dependency on groovy-all with required groovy package (#5879)
After removing groovy-all from clouddriver-yandex and clouddriver-oracle modules, encountered following errors while building and testing clouddriver respectively:

```
> Task :clouddriver-yandex:compileGroovy FAILED
/clouddriver/clouddriver-yandex/src/main/java/com/netflix/spinnaker/clouddriver/yandex/deploy/YandexServerGroupNameResolver.java:30: error: package org.apache.groovy.datetime.extensions does not exist
import org.apache.groovy.datetime.extensions.DateTimeExtensions;
                                            ^
1 error
startup failed:
Compilation failed; see the compiler error output for details.

1 error

FAILURE: Build failed with an exception.

```

```
> Task :clouddriver-oracle:compileTestGroovy
startup failed:
/clouddriver/clouddriver-oracle/src/test/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/op/DestroyOracleServerGroupAtomicOperationSpec.groovy: 24: unable to resolve class groovy.ui.SystemOutputInterceptor
 @ line 24, column 1.
   import groovy.ui.SystemOutputInterceptor
   ^

1 error

> Task :clouddriver-oracle:compileTestGroovy FAILED

```
To fix errors introduced the required groovy packages